# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "8.3.3"

    steps:
      - checkout
      - run: git checkout develop

      # Install Node Modules
      - run:
          name: Install Node Modules
          command: npm install

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: npm run test
