version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.13.0

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

  test:
    docker:
      - image: circleci/node:11.13.0

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

  deploy:
    docker:
      - image: getground/customer-frontend-pwa:2.0.1
    working_directory: /go/src/github.com/getground/customer-frontend-pwa
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
      - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run: gcloud app deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: develop
