# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.13.0

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # build!
      - run: npm run build
  test:
    docker:
      - image: circleci/node:11.13.0

    steps:
      # run tests!
      - run: npm test

  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/
    steps:
      - run: echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
      - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

      - run:
          name: deploy
          command: ./deploy-staging.sh

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
          requires:
            - test
      - test
      - deploy:
          requires:
            - build
            - test
